// PACKAGES PAGE
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { maintenancePackages, getMaintenancePackage } from '@/lib/data/packages-database';
import { Breadcrumb } from '@/components/navigation/Breadcrumb';
import { CTASection, FAQSection } from '@/components/pseo';
interface PageProps { params: Promise<{ slug: string }>; }
export async function generateStaticParams() { return maintenancePackages.map((p) => ({ slug: p.slug })); }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const rp = await params; const pkg = getMaintenancePackage(rp.slug); if (!pkg) return { title: 'Not Found' }; return { title: pkg.name + ' | L' + pkg.monthlyPrice + '/month | Hampstead Renovations', description: pkg.description, alternates: { canonical: 'https://hampsteadrenovations.co.uk/packages/' + rp.slug } }; }
export default async function PackagePage({ params }: PageProps) { const rp = await params; const pkg = getMaintenancePackage(rp.slug); if (!pkg) notFound(); const bc = [{ name: 'Home', href: '/' }, { name: 'Packages', href: '/packages' }, { name: pkg.name, href: '/packages/' + rp.slug, current: true }]; return (<main className="min-h-screen"><section className="bg-gradient-to-br from-blue-900 to-slate-800 text-white py-16"><div className="container mx-auto px-4"><Breadcrumb items={bc} className="mb-6" /><span className="inline-block bg-blue-500/20 text-blue-300 px-4 py-1 rounded-full text-sm mb-4">{pkg.tier.toUpperCase()}</span><h1 className="text-4xl font-bold mb-2">{pkg.name}</h1><p className="text-xl text-blue-100 mb-4">{pkg.tagline}</p><div className="flex items-baseline gap-2"><span className="text-4xl font-bold">L{pkg.monthlyPrice}</span><span className="text-blue-200">/month</span></div><p className="text-sm text-blue-200 mt-2">or L{pkg.annualPrice}/year (save L{pkg.annualSaving})</p></div></section><section className="py-16 bg-white"><div className="container mx-auto px-4"><h2 className="text-3xl font-bold mb-8">Whats Covered</h2><ul className="grid md:grid-cols-2 gap-4">{pkg.coverage.map((c, i) => <li key={i} className="flex items-start gap-3 bg-green-50 p-4 rounded-lg"><span className="text-green-500">*</span><span>{c}</span></li>)}</ul></div></section><section className="py-16 bg-slate-50"><div className="container mx-auto px-4"><h2 className="text-3xl font-bold mb-8">Details</h2><div className="grid md:grid-cols-3 gap-6"><div className="bg-white p-6 rounded-lg"><h3 className="font-semibold mb-2">Response Time</h3><p className="text-blue-600">{pkg.responseTime}</p></div><div className="bg-white p-6 rounded-lg"><h3 className="font-semibold mb-2">Callout Fee</h3><p className="text-blue-600">{pkg.calloutFee}</p></div><div className="bg-white p-6 rounded-lg"><h3 className="font-semibold mb-2">Parts</h3><p className="text-blue-600">{pkg.partsIncluded}</p></div></div></div></section><section className="py-16 bg-white"><div className="container mx-auto px-4"><h2 className="text-2xl font-bold mb-4">Ideal For</h2><ul className="flex flex-wrap gap-2">{pkg.idealFor.map((x, i) => <li key={i} className="bg-blue-100 text-blue-700 px-4 py-2 rounded-full text-sm">{x}</li>)}</ul></div></section><FAQSection faqs={pkg.faqs} title={pkg.name + ' FAQs'} /><CTASection cta={{ headline: 'Get ' + pkg.name, subtext: 'Start your coverage today.', buttonText: 'Sign Up', phoneNumber: '020 8000 0000' }} /></main>); }